#!/usr/bin/env node
/**
 * Cross-repo drift check for the wafermap ↔ tsmap pair.
 *
 * These two repos share a release handshake, a UI baseline and an agent config
 * layer, but live in separate folders with separate tooling — so they drift
 * silently. In August 2026 that drift had already produced four live failures
 * (a venv pointing at a pre-rename path, a semble MCP server registered in a
 * file that ignores the key, a stale absolute path in a "HARD RULE", and a
 * docs-site deploy ungated by tests). Every check below exists because
 * something in that class actually broke, not as a hypothetical.
 *
 * Usage:  node scripts/check-drift.mjs [--quiet]
 * Exit:   0 = no drift, 1 = drift found.
 *
 * This file is intentionally identical in both repos — it inspects the pair, so
 * it does not matter which side you run it from. If you change it, copy it to
 * the other repo (the check at the bottom enforces that).
 */

import { readFileSync, existsSync, readdirSync, lstatSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';

const HOME = homedir();
const SELF = fileURLToPath(import.meta.url);

// Derived, never hardcoded: this script lives at <repo>/scripts/check-drift.mjs,
// so the pair root is two levels up, and the sibling repo sits beside it. The
// whole reason this file exists is that hardcoded absolute paths went stale when
// a folder was renamed — it must not repeat that mistake itself. Moving both
// repos together requires no edit here.
const REPO = dirname(dirname(SELF));
const PAIR_ROOT = dirname(REPO);
const WAFERMAP = join(PAIR_ROOT, 'wafermap');
const TSMAP = join(PAIR_ROOT, 'tsmap');

const quiet = process.argv.includes('--quiet');
const problems = [];
const notes = [];

const fail = (area, msg, fix) => problems.push({ area, msg, fix });
const note = (msg) => notes.push(msg);

const read = (p) => (existsSync(p) ? readFileSync(p, 'utf8') : null);
const readJson = (p) => {
  const raw = read(p);
  if (raw === null) return null;
  try {
    return JSON.parse(raw);
  } catch {
    fail('json', `${p} is not valid JSON`, 'fix the syntax');
    return null;
  }
};

// ─── 1. Absolute paths that no longer exist ──────────────────────────────────
// The wmap → wafermap rename left stale absolute paths in CLAUDE.md, in the
// venv's pyvenv.cfg, and in every script shebang inside it. This check alone
// would have caught three of the four August 2026 failures.
function checkStalePaths() {
  // Only prose/config that is meant to describe reality. Deliberately NOT the
  // .claude/settings.json permission lists: those accumulate one-off entries
  // naming files that were transient by nature (a downloaded archive, a
  // version-pinned path in ~/.cargo/registry), so checking them is pure noise.
  const targets = [
    join(WAFERMAP, 'CLAUDE.md'),
    join(TSMAP, 'CLAUDE.md'),
    join(HOME, '.claude', 'CLAUDE.md'),
    join(WAFERMAP, 'UI_STANDARDS.md'),
    join(WAFERMAP, '.venv', 'pyvenv.cfg'),
    join(TSMAP, '.venv', 'pyvenv.cfg'),
  ];
  // Case-sensitive and anchored at the real home dir, so prose like
  // "Home/End/Enter" in a keyboard-shortcut list is not mistaken for a path.
  const pathRe = new RegExp(`${HOME}/[^\\s"'\`)>\\]]*`, 'g');
  for (const file of targets) {
    const body = read(file);
    if (body === null) continue;
    const seen = new Set();
    for (const m of body.matchAll(pathRe)) {
      // Trim trailing punctuation that belongs to the sentence, not the path.
      const p = m[0].replace(/[.,;:)*`]+$/, '');
      if (seen.has(p) || p.includes('*')) continue;
      seen.add(p);
      if (!existsSync(p)) {
        fail('stale-path', `${file}: references ${p}, which does not exist`,
          'update the path, or rebuild the venv if it is a venv path');
      }
    }
  }

  // Relative paths named in wafermap's CLAUDE.md — the "Package Structure" and
  // "Docs site" sections drifted when docs/API.md became docs/api.md and the
  // top-level /data/ moved under docs/.
  const wmapDoc = read(join(WAFERMAP, 'CLAUDE.md')) ?? '';
  for (const m of wmapDoc.matchAll(/\[[^\]]+\]\((?!https?:|#|\.\.\/)([^)#]+)\)/g)) {
    const rel = m[1];
    if (!existsSync(join(WAFERMAP, rel))) {
      fail('stale-path', `wafermap/CLAUDE.md links to ${rel}, which does not exist`,
        'fix the link — docs/ filenames are lowercase');
    }
  }
}

// ─── 2. venv health and zensical pin agreement ───────────────────────────────
// Both repos build their docs site with Zensical. wafermap pinned 0.0.43 while
// tsmap floated to whatever PyPI served — so the two sites were generated by
// different versions, and tsmap had no requirements.txt at all.
function checkZensical() {
  const pins = {};
  for (const [name, root] of [['wafermap', WAFERMAP], ['tsmap', TSMAP]]) {
    const req = read(join(root, 'requirements.txt'));
    if (req === null) {
      fail('zensical', `${name} has no requirements.txt`,
        'add one pinning zensical==X.Y.Z so CI cannot drift to latest');
      continue;
    }
    const pin = req.match(/zensical==([\d.]+)/)?.[1];
    if (!pin) {
      fail('zensical', `${name}/requirements.txt does not pin zensical`,
        'use an == pin, not a range');
      continue;
    }
    pins[name] = pin;

    const bin = join(root, '.venv', 'bin', 'zensical');
    if (!existsSync(bin)) {
      fail('zensical', `${name} has no .venv/bin/zensical`,
        `cd ${root} && python3 -m venv .venv && .venv/bin/pip install -r requirements.txt`);
      continue;
    }
    let installed;
    try {
      installed = execFileSync(bin, ['--version'], { encoding: 'utf8' }).trim();
    } catch (err) {
      fail('zensical', `${name}: .venv/bin/zensical will not run (${err.message.split('\n')[0]})`,
        `rebuild the venv: cd ${root} && rm -rf .venv && python3 -m venv .venv && .venv/bin/pip install -r requirements.txt`);
      continue;
    }
    if (installed !== pin) {
      fail('zensical', `${name}: venv has zensical ${installed} but requirements.txt pins ${pin}`,
        `cd ${root} && .venv/bin/pip install -r requirements.txt`);
    }
  }
  if (pins.wafermap && pins.tsmap && pins.wafermap !== pins.tsmap) {
    fail('zensical', `pins disagree: wafermap ${pins.wafermap} vs tsmap ${pins.tsmap}`,
      'converge them — the two docs sites should be built by the same generator');
  }

  // CI must install from the pin, not float.
  for (const [name, root] of [['wafermap', WAFERMAP], ['tsmap', TSMAP]]) {
    const wf = read(join(root, '.github', 'workflows', 'deploy.yml'));
    if (wf && /pip install zensical(?!\S)/.test(wf)) {
      fail('zensical', `${name}/deploy.yml runs an unpinned \`pip install zensical\``,
        'change to `pip install -r requirements.txt`');
    }
  }
}

// ─── 3. MCP server registration ──────────────────────────────────────────────
// `mcpServers` is not a valid key in .claude/settings.json — Claude Code
// silently ignores it there. tsmap carried such a block for months believing
// semble was configured. The project-scoped mechanism is .mcp.json.
function checkMcp() {
  for (const [name, root] of [['wafermap', WAFERMAP], ['tsmap', TSMAP]]) {
    const settings = readJson(join(root, '.claude', 'settings.json'));
    if (settings && 'mcpServers' in settings) {
      fail('mcp', `${name}/.claude/settings.json contains an "mcpServers" key`,
        'move it to .mcp.json — settings.json ignores that key entirely');
    }
    const mcp = readJson(join(root, '.mcp.json'));
    if (!mcp?.mcpServers?.semble) {
      fail('mcp', `${name} has no semble server in .mcp.json`,
        'add it, or drop the semble preference from the CLAUDE.md files');
    }
  }

  // A configured server whose command is not installed is worse than none —
  // the CLAUDE.md rule then mandates a tool that cannot start.
  const mcp = readJson(join(WAFERMAP, '.mcp.json'));
  const cmd = mcp?.mcpServers?.semble?.command;
  if (cmd && !onPath(cmd)) {
    fail('mcp', `.mcp.json declares semble via "${cmd}", which is not on PATH`,
      `install it (e.g. \`curl -LsSf https://astral.sh/uv/install.sh | sh\` for uv), or remove the server and the rule that depends on it`);
  }
}

function onPath(cmd) {
  try {
    execFileSync('sh', ['-c', `command -v ${cmd}`], { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

// ─── 4. Shared agent layer is not re-forked per repo ─────────────────────────
// semble-search.md was byte-identical in both repos. Duplicated agents drift.
function checkAgents() {
  const shared = join(HOME, '.claude', 'agents');
  for (const [name, root] of [['wafermap', WAFERMAP], ['tsmap', TSMAP]]) {
    const dir = join(root, '.claude', 'agents');
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir)) {
      if (existsSync(join(shared, f))) {
        fail('agents', `${name}/.claude/agents/${f} shadows the shared ~/.claude/agents/${f}`,
          'delete the per-repo copy; the shared one applies to both');
      }
    }
  }
}

// ─── 5. Shared devDependency versions agree ──────────────────────────────────
// Both repos run the same toolchain over the same guide/screenshot scripts.
// A typescript or marked skew shows up as "works in one repo only".
function checkSharedDeps() {
  const a = readJson(join(WAFERMAP, 'package.json'));
  const b = readJson(join(TSMAP, 'package.json'));
  if (!a || !b) return;
  for (const dep of ['typescript', 'marked', 'playwright']) {
    const va = a.devDependencies?.[dep];
    const vb = b.devDependencies?.[dep];
    if (va && vb && va !== vb) {
      fail('deps', `${dep} differs: wafermap ${va} vs tsmap ${vb}`,
        'align them — both repos run the same guide/screenshot scripts');
    }
  }
}

// ─── 6. The wmap ↔ tsmap release handshake is in a shippable state ───────────
function checkHandshake() {
  const wmapPkg = readJson(join(WAFERMAP, 'package.json'));
  const tsPkg = readJson(join(TSMAP, 'package.json'));
  if (!wmapPkg || !tsPkg) return;

  const linked = join(TSMAP, 'node_modules', '@wafertools', 'wafermap');
  const isLink = lstatSync(linked, { throwIfNoEntry: false })?.isSymbolicLink() ?? false;
  if (isLink) {
    note(`tsmap is currently LINKED to ../wafermap — expected mid-batch, but it ` +
         `must be unlinked and re-pinned before any tsmap release ` +
         `(npm run wmap:unlink).`);
    return;
  }

  const range = tsPkg.dependencies?.['@wafertools/wafermap'];
  const published = wmapPkg.version;
  if (range && published && !range.includes(published)) {
    note(`tsmap pins @wafertools/wafermap ${range} but the local wafermap tree ` +
         `is at ${published} — expected while a wmap release is unpublished; ` +
         `bump tsmap once it is on npm.`);
  }
}

// ─── 7. This script itself has not forked ────────────────────────────────────
function checkSelfCopies() {
  const other = SELF.startsWith(WAFERMAP)
    ? join(TSMAP, 'scripts', 'check-drift.mjs')
    : join(WAFERMAP, 'scripts', 'check-drift.mjs');
  const mine = read(SELF);
  const theirs = read(other);
  if (theirs === null) {
    fail('self', `${other} is missing`, `copy this file there — it checks the pair, not one side`);
  } else if (theirs !== mine) {
    fail('self', `check-drift.mjs differs between the two repos`,
      `copy the newer one over: cp ${SELF} ${other}`);
  }
}

// ─── run ─────────────────────────────────────────────────────────────────────
checkStalePaths();
checkZensical();
checkMcp();
checkAgents();
checkSharedDeps();
checkHandshake();
checkSelfCopies();

if (notes.length && !quiet) {
  for (const n of notes) console.log(`  note: ${n}\n`);
}

if (problems.length === 0) {
  if (!quiet) console.log('✓ no drift between wafermap and tsmap');
  process.exit(0);
}

console.error(`\n✗ ${problems.length} drift issue${problems.length === 1 ? '' : 's'}:\n`);
for (const { area, msg, fix } of problems) {
  console.error(`  [${area}] ${msg}`);
  console.error(`      fix: ${fix}\n`);
}
process.exit(1);
