#!/usr/bin/env node
// Regenerates packages/canvas-adapter/version.ts from package.json's version,
// stamped with the build time. Run via: node scripts/sync-version.mjs
// Also called automatically as part of `npm run build`.
//
// The build timestamp exists specifically for linked local dev (`npm link` /
// `wmap:link` in a consuming host): package.json's version does not change
// between edits during that workflow, so it alone can't tell a host which
// rebuild is actually loaded. The timestamp changes on every `npm run build`,
// so logWmapVersionOnce() (toolbar.ts) always prints something distinguishable.

import { readFileSync, writeFileSync } from 'node:fs';

const outFile = new URL('../packages/canvas-adapter/version.ts', import.meta.url);
const pkg     = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

const output = `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit directly.
// Regenerated on every \`npm run build\`.

export const WMAP_VERSION = ${JSON.stringify(pkg.version)};
export const WMAP_BUILD_TIME = ${JSON.stringify(new Date().toISOString())};
`;

writeFileSync(outFile, output, 'utf8');
console.log(`sync-version: wrote packages/canvas-adapter/version.ts (v${pkg.version}, ${new Date().toISOString()})`);
