#!/usr/bin/env node
// Reads SVG files from docs/images/icons/ and regenerates packages/canvas-adapter/icons.ts.
// Run via: node scripts/sync-icons.mjs
// Also called automatically as part of `npm run build`.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root    = fileURLToPath(new URL('..', import.meta.url));
const iconDir = join(root, 'docs/images/icons');
const outFile = join(root, 'packages/canvas-adapter/icons.ts');

const files = readdirSync(iconDir)
  .filter(f => f.endsWith('.svg'))
  .sort();

const entries = files.map(file => {
  const key = basename(file, '.svg');
  // SVG files use a hardcoded colour for doc rendering (currentColor doesn't work in <img> tags).
  // Restore currentColor for the toolbar, which injects SVGs as innerHTML and inherits CSS colour.
  const svg = readFileSync(join(iconDir, file), 'utf8').trim()
    .replace(/ xmlns="http:\/\/www\.w3\.org\/2000\/svg"/, '')
    .replace(/stroke="#[0-9a-fA-F]{6}"/g, 'stroke="currentColor"')
    .replace(/fill="#[0-9a-fA-F]{6}"/g,   'fill="currentColor"');
  return `  ${key.padEnd(12)}: \`${svg}\``;
});

const output = `// ── Toolbar icon set ──────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/sync-icons.mjs — do not edit directly.
// Edit the source SVG files in docs/images/icons/ then run: node scripts/sync-icons.mjs
// Internal shared module. Do not re-export from index.ts.

export const ICONS: Record<string, string> = {
${entries.join(',\n')},
};
`;

writeFileSync(outFile, output, 'utf8');
console.log(`sync-icons: wrote ${files.length} icons to packages/canvas-adapter/icons.ts`);
