import type { Wafer } from '../core/wafer.js';
import type { Die } from '../core/dies.js';
import type { Reticle } from '../core/reticle.js';
import type { DieMetadata, WaferMetadata } from '../core/metadata.js';
import { rotatePoint } from '../core/transforms.js';
import { contrastTextColor } from './colorMap.js';
import { getColorScheme } from './colorSchemes.js';
import type { TestDef, BinDef } from './buildWaferMap.js';
import { getDieTestValue } from './buildWaferMap.js';
import { fmt, fmtColorbarAxis } from './fmt.js';

type BinDefMap = Map<number, BinDef>;

/** Resolve a toolbar testIndex cursor to the canonical test number for getDieTestValue. */
function resolveTestNumber(testIndex: number, testDefs?: TestDef[]): { testNumber: number; fallbackIndex: number } {
  if (testDefs?.length) {
    const def = testDefs.find(t => (t.index ?? t.testNumber) === testIndex)
             ?? testDefs[0]; // default to first test when testIndex doesn't match any def
    return {
      testNumber:    def.testNumber ?? def.index ?? testIndex,
      fallbackIndex: def.index     ?? testIndex,
    };
  }
  return { testNumber: testIndex, fallbackIndex: testIndex };
}

export type PlotMode = 'value' | 'hardBin' | 'softBin' | 'stackedValues' | 'stackedBins' | 'stackedSoftBins' | 'specLimit';

interface Point {
  x: number;
  y: number;
}

export interface SceneRect {
  x: number;
  y: number;
  width: number;
  height: number;
  fill: string | number;
  type: 'hardBin' | 'softBin' | 'value' | 'stacked';
  stack?: number[];
  metadata?: DieMetadata;
  path: string;
}

export interface SceneText {
  x: number;
  y: number;
  text: string;
  fontSize: number;
  color: string;
  align: 'center';
}

export interface SceneHoverPoint {
  x: number;
  y: number;
  text: string;
}

export interface SceneOverlay {
  kind: 'wafer-boundary' | 'reticle' | 'probe-path' | 'ring-boundary' | 'quadrant-boundary' | 'xy-indicator';
  path: string;
  lineColor: string;
  lineWidth: number;
  fill?: string;
}

export interface Scene {
  rectangles: SceneRect[];
  hoverPoints: SceneHoverPoint[];
  texts: SceneText[];
  overlays: SceneOverlay[];
  plotMode: PlotMode;
  colorScheme: string;
  metadata: WaferMetadata | null;
  dies: Die[];
  /** Actual [min, max] of the value data used for color normalization. */
  valueRange: [number, number];
  /** Named test definitions — populated when `testDefs` is passed to `buildWaferMap`. */
  testDefs?: TestDef[];
  /** Named hard bin definitions (for `die.hbin`). Independent number space from soft bins. */
  hbinDefs?: BinDef[];
  /** Named soft bin definitions (for `die.sbin`). Independent number space from hard bins. */
  sbinDefs?: BinDef[];
  /** Which `values[]` index is being displayed (for `value` plot mode). Default 0. */
  testIndex: number;
  /** True when log₁₀ scale is both requested and valid (vMin > 0). */
  logScale: boolean;
  /** Aggregation method label for `stackedValues` hover tooltips (e.g. `'mean'`). */
  aggrMethod?: string;
  /** Total wafers in lot — for `stackedBins` hover percentage calculation. */
  lotSize?: number;
  /** Total effective axis flip for tick labels (data-pipeline flip XOR interactive flip). */
  axisFlip: { x: boolean; y: boolean };
  /** Total effective rotation in degrees (wafer orientation + interactive rotation). */
  rotation: number;
  /** True when reticle geometry is present — used to conditionally show the reticle toolbar button. */
  hasReticle: boolean;
  /** True when the scene was built from lot-aggregated data (lotStack). Controls toolbar stacked-mode visibility. */
  isLotStack: boolean;
  /** Wafer centre in scene/display mm coordinates (the rotation pivot). */
  waferCenter: { x: number; y: number };
  /** Wafer radius in mm. */
  waferRadius: number;
  /** Unit vector pointing toward the notch/flat in display space (post-transform). Null when no notch. */
  notchDir: { x: number; y: number } | null;
}

export interface SceneOptions {
  plotMode?: PlotMode;
  showText?: boolean;
  showReticle?: boolean;
  showProbePath?: boolean;
  ringCount?: number;
  showRingBoundaries?: boolean;
  showQuadrantBoundaries?: boolean;
  showXYIndicator?: boolean;
  dieGap?: number;
  /** Named colour scheme — any scheme registered via registerColorScheme(). Default: 'default'. */
  colorScheme?: string;
  highlightBin?: number;
  interactiveTransform?: { rotation?: number; flipX?: boolean; flipY?: boolean };
  /**
   * Explicit [min, max] for value colour normalization. When omitted the range
   * is auto-computed from the die values present in the scene.
   */
  valueRange?: [number, number];
  /**
   * Controls the default colorbar range when the active testDef has spec limits.
   * `'spec'` (default when limits present): colorbar spans [limitLow, limitHigh].
   * `'data'`: colorbar spans the actual data min/max regardless of limits.
   */
  colorbarRangeMode?: 'spec' | 'data';
  /**
   * Reticle rectangles to overlay on the map.
   * Generated by `generateReticleGrid` or the `reticle` option on `buildWaferMap`.
   */
  reticles?: Reticle[];
  /** Named test definitions — one per `values[]` entry. */
  testDefs?: TestDef[];
  /**
   * Named hard bin definitions — one per distinct `die.hbin` value.
   * Hard and soft bin number spaces are independent (STDF V4: both 0–32767).
   */
  hbinDefs?: BinDef[];
  /**
   * Named soft bin definitions — one per distinct `die.sbin` value.
   * Soft bins are the logical test-program classification; hard bins are the physical sort result.
   */
  sbinDefs?: BinDef[];
  /**
   * Which `values[]` index to display in `value` plot mode. Default `0`.
   * When `testDefs` is provided, the toolbar mode dropdown offers one item per test.
   */
  testIndex?: number;
  /**
   * When true, apply log₁₀ scale to value normalization and the colorbar.
   * Overrides the per-test `TestDef.logScale` default.
   * Falls back to linear when vMin ≤ 0.
   */
  logScale?: boolean;
  /**
   * Format to use for unitless values outside the normal display range [0.1, 9999].
   * `'engineering'` (default): multiples-of-3 exponent notation (e.g. `12E-6`).
   * `'si'`: SI prefix with no unit suffix (e.g. `12 µ`).
   * Values with a unit always use SI prefix regardless of this setting.
   */
  fallbackFormat?: 'si' | 'engineering';
  /**
   * Aggregation method label shown in hover tooltips for `stackedValues` mode.
   * E.g. `'mean'`, `'median'`, `'stddev'`, `'min'`, `'max'`.
   */
  aggrMethod?: string;
  /**
   * Total number of wafers in the lot — used to compute bin occurrence percentage
   * in `stackedBins` hover tooltips.
   */
  lotSize?: number;
  /**
   * Axis flip baked in by the data pipeline (for LL/LR/UL/UR origins or explicit
   * `xAxisDirection`/`yAxisDirection`). Combined with `interactiveTransform` flip
   * to produce the total effective axis flip for tick labels.
   */
  dataAxisFlip?: { x: boolean; y: boolean };
  /** Set to true when the scene is built from lot-aggregated data (lotStack). */
  isLotStack?: boolean;
}


interface TransformState {
  rotation: number;
  flipX: boolean;
  flipY: boolean;
}

interface ColorFns {
  forValue: (t: number) => string;
  forBin: (bin: number) => string;
}

const PARTIAL_DIE_FILL = '#d3d6db';
const DIM_FILL = '#e8e9ea';
const EDGE_EXCLUDED_FILL = '#eceef0';
const SPEC_PASS_FILL   = '#2ecc71';
const SPEC_FAIL_LOW    = '#3498db';
const SPEC_FAIL_HIGH   = '#e74c3c';
const NO_DATA_FILL     = '#d6d9dd';

function normalizeTransform(
  wafer: Wafer,
  interactiveTransform: SceneOptions['interactiveTransform']
): TransformState {
  return {
    rotation: wafer.orientation + (interactiveTransform?.rotation ?? 0),
    flipX: interactiveTransform?.flipX ?? false,
    flipY: interactiveTransform?.flipY ?? false,
  };
}

function transformVector(dx: number, dy: number, transform: TransformState): Point {
  const rad = (transform.rotation * Math.PI) / 180;
  const cos = Math.cos(rad);
  const sin = Math.sin(rad);
  let x = dx * cos - dy * sin;
  let y = dx * sin + dy * cos;

  if (transform.flipX) x = -x;
  if (transform.flipY) y = -y;

  return { x, y };
}

function toPath(points: Point[]): string {
  return `${points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`).join(' ')} Z`;
}

function polylinePath(points: Point[], close = false): string {
  if (!points.length) return '';
  const path = points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`).join(' ');
  return close ? `${path} Z` : path;
}

function transformPoint(point: Point, center: Point, transform: TransformState): Point {
  let next = transform.rotation ? rotatePoint(point.x, point.y, transform.rotation, center.x, center.y) : point;
  if (transform.flipX) next = { x: 2 * center.x - next.x, y: next.y };
  if (transform.flipY) next = { x: next.x, y: 2 * center.y - next.y };
  return next;
}

/**
 * Returns the boundary point at `angle` for a wafer with an orientation flat
 * (chord cut).  V-notch wafers are handled separately in buildBoundaryOverlay.
 */
function boundaryPointAtAngle(wafer: Wafer, angle: number): Point {
  const { center, radius, notch } = wafer;
  let x = center.x + radius * Math.cos(angle);
  let y = center.y + radius * Math.sin(angle);

  if (!notch) return { x, y };

  const chordDist = Math.sqrt(radius ** 2 - (notch.length / 2) ** 2);
  const halfLen   = notch.length / 2;
  const dx = x - center.x;
  const dy = y - center.y;

  if (notch.type === 'bottom' && dy < -chordDist) {
    y = center.y - chordDist;
    x = center.x + Math.max(-halfLen, Math.min(halfLen, dx));
  } else if (notch.type === 'top' && dy > chordDist) {
    y = center.y + chordDist;
    x = center.x + Math.max(-halfLen, Math.min(halfLen, dx));
  } else if (notch.type === 'left' && dx < -chordDist) {
    x = center.x - chordDist;
    y = center.y + Math.max(-halfLen, Math.min(halfLen, dy));
  } else if (notch.type === 'right' && dx > chordDist) {
    x = center.x + chordDist;
    y = center.y + Math.max(-halfLen, Math.min(halfLen, dy));
  }

  return { x, y };
}

function rectanglePath(center: Point, width: number, height: number, transform: TransformState): string {
  const corners = [
    transformVector(-width / 2, -height / 2, transform),
    transformVector(width / 2, -height / 2, transform),
    transformVector(width / 2, height / 2, transform),
    transformVector(-width / 2, height / 2, transform),
  ].map((corner) => ({ x: center.x + corner.x, y: center.y + corner.y }));

  return toPath(corners);
}

function formatValueLabel(values: number[], tickFmt: (v: number) => string): string {
  return values.map(tickFmt).join(' / ');
}


function fontSizeForDie(die: Die, text: string): number {
  const minSide = Math.max(1, Math.min(die.width, die.height));
  const widthBudget = die.width / Math.max(text.length, 1);
  return Math.max(8, Math.min(16, Math.round(Math.min(minSide * 0.55, widthBudget * 1.8))));
}

function buildHoverText(
  die: Die,
  plotMode: PlotMode,
  testDefs?: TestDef[],
  hbinDefs?: BinDef[],
  sbinDefs?: BinDef[],
  fallbackFormat?: 'si' | 'engineering',
  aggrMethod?: string,
  lotSize?: number,
): string {
  const lines: string[] = [`Die (${die.x}, ${die.y})`];

  if (plotMode === 'stackedValues') {
    // Aggregated scalar is stored in testValues[0] (preferred) or values[0] (deprecated).
    const v = getDieTestValue(die, 0, 0);
    if (v !== undefined) {
      const def   = testDefs?.[0];
      const tn    = def?.testNumber ?? def?.index;
      const name  = def?.name ?? (tn != null ? `Test ${tn}` : 'Value');
      const method = aggrMethod ? ` (${aggrMethod})` : '';
      lines.push(`${name}${method}: ${fmt(v, def?.unit, fallbackFormat)}`);
    }
  } else if (plotMode === 'stackedBins' || plotMode === 'stackedSoftBins') {
    const count = getDieTestValue(die, 0, 0);
    const bin   = plotMode === 'stackedSoftBins' ? die.sbin : die.hbin;
    if (count !== undefined) {
      const pct     = lotSize ? ` (${((count / lotSize) * 100).toFixed(0)}%)` : '';
      const defMap  = plotMode === 'stackedSoftBins'
        ? (sbinDefs ? new Map(sbinDefs.map(d => [d.bin, d])) : null)
        : (hbinDefs ? new Map(hbinDefs.map(d => [d.bin, d])) : null);
      const binLabel = bin !== undefined
        ? (defMap?.get(bin)?.name ? `${bin} · ${defMap.get(bin)!.name}` : `Bin ${bin}`)
        : 'Bin';
      lines.push(`${binLabel}: ${count}${pct}`);
    }
  } else {
    // Standard modes: show all test values with names, then bins.
    if (die.testValues && Object.keys(die.testValues).length > 0) {
      if (testDefs?.length) {
        const parts = testDefs.map(def => {
          const tn  = def.testNumber ?? def.index;
          if (tn === undefined) return null;
          const v = getDieTestValue(die, tn, def.index);
          if (v === undefined) return null;
          return `${def.name}: ${fmt(v, def.unit, fallbackFormat)}`;
        }).filter((s): s is string => s !== null);
        if (parts.length) lines.push(parts.join('<br>'));
      } else {
        const parts = Object.entries(die.testValues).map(([k, v]) =>
          `Test ${k}: ${fmt(v, undefined, fallbackFormat)}`
        );
        if (parts.length) lines.push(parts.join('<br>'));
      }
    } else if (die.values?.length) {
      // Deprecated fallback.
      if (testDefs?.length) {
        const parts = die.values.map((v, i) => {
          const def   = testDefs.find(t => t.index === i);
          const label = def?.name ?? `Test ${i}`;
          return `${label}: ${fmt(v, def?.unit, fallbackFormat)}`;
        });
        lines.push(parts.join('<br>'));
      } else {
        lines.push(`Values: ${die.values.map((v) => fmt(v, undefined, fallbackFormat)).join(' / ')}`);
      }
    }

    if (die.hbin !== undefined || die.sbin !== undefined) {
      const hbinMap = hbinDefs ? new Map(hbinDefs.map(d => [d.bin, d])) : null;
      const sbinMap = sbinDefs ? new Map(sbinDefs.map(d => [d.bin, d])) : null;
      const parts: string[] = [];
      if (die.hbin !== undefined) {
        const name  = hbinMap?.get(die.hbin)?.name;
        const value = name ? `${die.hbin} · ${name}` : String(die.hbin);
        parts.push(`HBin: ${value}`);
      }
      if (die.sbin !== undefined) {
        const name  = sbinMap?.get(die.sbin)?.name;
        const value = name ? `${die.sbin} · ${name}` : String(die.sbin);
        parts.push(`SBin: ${value}`);
      }
      lines.push(parts.join(' &nbsp;·&nbsp; '));
    }
  }

  if (die.retestCount !== undefined) lines.push(`Retests: ${die.retestCount}`);
  if (die.partial) lines.push('<i>partial die</i>');
  if (die.probeIndex !== undefined) lines.push(`Probe: #${die.probeIndex}`);

  if (die.metadata) {
    for (const [key, value] of Object.entries(die.metadata)) {
      if (value === undefined || value === null || key === 'customFields') continue;
      lines.push(`${key}: ${String(value)}`);
    }
    if (die.metadata.customFields) {
      for (const [key, value] of Object.entries(die.metadata.customFields)) {
        if (value === undefined || value === null) continue;
        lines.push(`${key}: ${String(value)}`);
      }
    }
  }

  return lines.join('<br>');
}


export function generateTextOverlay(
  dies: Die[],
  options: {
    plotMode: PlotMode;
    colorFns: ColorFns;
    normalize: (v: number) => number;
    testIndex: number;
    valueRange: [number, number];
    testDefs?: TestDef[];
    fallbackFormat?: 'si' | 'engineering';
  },
): SceneText[] {
  const { plotMode, colorFns, normalize, testIndex, valueRange, testDefs, fallbackFormat } = options;

  // Build a tick formatter matched to the colorbar scale so die labels are consistent.
  const testDef = testDefs?.find(t => (t.index ?? t.testNumber) === testIndex);
  const { tickFmt } = fmtColorbarAxis(valueRange[1], testDef?.name, testDef?.unit, fallbackFormat);
  const { testNumber: tn, fallbackIndex: fi } = resolveTestNumber(testIndex, testDefs);

  return dies.flatMap((die) => {
    let text = '';
    let color = '#111111';

    if (plotMode === 'value') {
      const v = getDieTestValue(die, tn, fi);
      if (v === undefined) return [];
      text = formatValueLabel([v], tickFmt);
      color = contrastTextColor(colorFns.forValue(normalize(v)));
    } else if (plotMode === 'hardBin' || plotMode === 'softBin') {
      const bin = plotMode === 'softBin' ? die.sbin : die.hbin;
      if (bin === undefined) return [];
      text = String(bin);
      color = contrastTextColor(colorFns.forBin(bin));
    } else {
      // stackedValues / stackedBins: aggregated scalar in testValues[0] or values[0]
      const v = getDieTestValue(die, 0, 0);
      if (v === undefined) return [];
      text = formatValueLabel([v], tickFmt);
      color = contrastTextColor(colorFns.forValue(normalize(v)));
    }

    return [{
      x: die.physX,
      y: die.physY,
      text,
      fontSize: fontSizeForDie(die, text),
      color,
      align: 'center',
    }];
  });
}

/**
 * Notch direction angle in radians.
 * Wafer convention: bottom notch points downward (−Y), which is angle −π/2.
 */
function notchAngle(type: 'top' | 'bottom' | 'left' | 'right'): number {
  if (type === 'top')    return  Math.PI / 2;
  if (type === 'bottom') return -Math.PI / 2;
  if (type === 'left')   return  Math.PI;
  return 0; // right
}

/**
 * Build the wafer boundary overlay, choosing between two rendering modes:
 *
 * - **Flat** (≤ 150 mm): straight chord cut — `boundaryPointAtAngle` handles it.
 * - **V-notch** (> 150 mm): three explicit points (entry → apex → exit) are
 *   spliced into the uniform circle trace so the notch renders as a sharp
 *   triangular indentation (~3.5 mm wide, ~1.25 mm deep — SEMI M1 standard).
 */
function buildBoundaryOverlay(wafer: Wafer, transform: TransformState, steps = 720): SceneOverlay[] {
  const { center, radius, notch } = wafer;

  // Determine rendering style from diameter — same threshold used in resolveNotch.
  const isVNotch = notch !== undefined && wafer.diameter > 150;

  if (!isVNotch) {
    // Flat / no alignment feature — uniform angle sweep with chord clamping.
    const points: Point[] = [];
    for (let index = 0; index <= steps; index++) {
      const angle = (2 * Math.PI * index) / steps;
      points.push(transformPoint(boundaryPointAtAngle(wafer, angle), center, transform));
    }
    return [{ kind: 'wafer-boundary', path: polylinePath(points, true), lineColor: '#111111', lineWidth: 2 }];
  }

  // V-notch: build circle, then splice in the triangular indentation.
  // SEMI M1: half-width at surface ≈ 1.75 mm, depth ≈ 1.25 mm.
  const notchDepth     = 1.25;
  const notchHalfWidth = notch.length; // set by createWafer = 1.75 for large wafers
  const θ0             = notchAngle(notch.type);
  const Δ              = Math.atan2(notchHalfWidth, radius); // angular half-span (~0.67° for 300 mm)
  const apexRadius     = radius - notchDepth;

  // Collect uniform circle points, skipping any that fall inside the notch zone.
  const points: Point[] = [];
  let notchInserted = false;

  for (let index = 0; index <= steps; index++) {
    const angle = (2 * Math.PI * index) / steps;

    // Normalise angle difference to (−π, π].
    let dθ = angle - θ0;
    while (dθ >  Math.PI) dθ -= 2 * Math.PI;
    while (dθ < -Math.PI) dθ += 2 * Math.PI;

    if (Math.abs(dθ) <= Δ) {
      // Inside the notch arc — insert V geometry once at this crossing.
      if (!notchInserted) {
        notchInserted = true;
        const entry = { x: center.x + radius * Math.cos(θ0 - Δ), y: center.y + radius * Math.sin(θ0 - Δ) };
        const apex  = { x: center.x + apexRadius * Math.cos(θ0), y: center.y + apexRadius * Math.sin(θ0) };
        const exit_ = { x: center.x + radius * Math.cos(θ0 + Δ), y: center.y + radius * Math.sin(θ0 + Δ) };
        points.push(
          transformPoint(entry, center, transform),
          transformPoint(apex,  center, transform),
          transformPoint(exit_, center, transform),
        );
      }
      continue;
    }

    points.push(transformPoint({ x: center.x + radius * Math.cos(angle), y: center.y + radius * Math.sin(angle) }, center, transform));
  }

  return [{ kind: 'wafer-boundary', path: polylinePath(points, true), lineColor: '#111111', lineWidth: 2 }];
}

function buildRingOverlays(wafer: Wafer, transform: TransformState, ringCount: number, steps = 360): SceneOverlay[] {
  const overlays: SceneOverlay[] = [];
  const safeRingCount = Math.max(1, Math.floor(ringCount));

  for (let ring = 1; ring < safeRingCount; ring++) {
    const radius = (wafer.radius * ring) / safeRingCount;
    const points: Point[] = [];

    for (let index = 0; index <= steps; index++) {
      const angle = (2 * Math.PI * index) / steps;
      const localPoint = {
        x: wafer.center.x + radius * Math.cos(angle),
        y: wafer.center.y + radius * Math.sin(angle),
      };
      points.push(transformPoint(localPoint, wafer.center, transform));
    }

    overlays.push({
      kind: 'ring-boundary',
      path: polylinePath(points, true),
      lineColor: 'rgba(255,255,255,0.7)',
      lineWidth: 1.5,
    });
  }

  return overlays;
}

function buildQuadrantOverlays(wafer: Wafer, transform: TransformState): SceneOverlay[] {
  const angles = [0, Math.PI / 2];

  return angles.map((angle) => {
    const start = transformPoint(boundaryPointAtAngle(wafer, angle), wafer.center, transform);
    const end = transformPoint(boundaryPointAtAngle(wafer, angle + Math.PI), wafer.center, transform);
    return {
      kind: 'quadrant-boundary',
      path: polylinePath([start, end]),
      lineColor: 'rgba(255,255,255,0.7)',
      lineWidth: 1.5,
    };
  });
}

function buildReticleOverlays(reticles: Reticle[], wafer: Wafer, transform: TransformState): SceneOverlay[] {
  return reticles.map((reticle) => {
    const rotatedCenter = transform.rotation
      ? rotatePoint(reticle.x, reticle.y, transform.rotation, wafer.center.x, wafer.center.y)
      : { x: reticle.x, y: reticle.y };

    const transformedCenter = {
      x: transform.flipX ? 2 * wafer.center.x - rotatedCenter.x : rotatedCenter.x,
      y: transform.flipY ? 2 * wafer.center.y - rotatedCenter.y : rotatedCenter.y,
    };

    return {
      kind: 'reticle',
      path: rectanglePath(transformedCenter, reticle.width, reticle.height, transform),
      lineColor: 'rgba(0,100,220,0.45)',
      lineWidth: 1,
      fill: 'rgba(0,0,0,0)',
    };
  });
}

function buildProbeOverlay(dies: Die[]): SceneOverlay[] {
  const ordered = dies
    .filter((die) => die.probeIndex !== undefined)
    .sort((left, right) => (left.probeIndex ?? 0) - (right.probeIndex ?? 0));

  if (!ordered.length) return [];

  return [{
    kind: 'probe-path',
    path: polylinePath(ordered.map((die) => ({ x: die.physX, y: die.physY }))),
    lineColor: 'rgba(220,80,0,0.55)',
    lineWidth: 1,
  }];
}

function pushDieRectangles(
  rectangles: SceneRect[],
  die: Die,
  plotMode: PlotMode,
  transform: TransformState,
  gap: number,
  colorFns: ColorFns,
  highlightBin: number | undefined,
  normalize: (v: number) => number,
  testNumber: number,
  fallbackIndex: number,
  binDefMap: Map<number, BinDef> | null,
  activeTestDef?: TestDef,
): void {
  const rw = die.width - gap;
  const rh = die.height - gap;

  const getBin = (d: Die) => plotMode === 'softBin' ? d.sbin : d.hbin;

  if (die.partial) {
    rectangles.push({
      x: die.physX, y: die.physY, width: rw, height: rh,
      fill: PARTIAL_DIE_FILL, type: 'stacked', metadata: die.metadata,
      path: rectanglePath({ x: die.physX, y: die.physY }, rw, rh, transform),
    });
    return;
  }

  if (die.edgeExcluded) {
    rectangles.push({
      x: die.physX, y: die.physY, width: rw, height: rh,
      fill: EDGE_EXCLUDED_FILL, type: 'stacked', metadata: die.metadata,
      path: rectanglePath({ x: die.physX, y: die.physY }, rw, rh, transform),
    });
    return;
  }

  if (highlightBin !== undefined &&
      (plotMode === 'hardBin' || plotMode === 'softBin') &&
      getBin(die) !== highlightBin) {
    rectangles.push({
      x: die.physX, y: die.physY, width: rw, height: rh,
      fill: DIM_FILL, type: 'hardBin', metadata: die.metadata,
      path: rectanglePath({ x: die.physX, y: die.physY }, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'specLimit') {
    const value = getDieTestValue(die, testNumber, fallbackIndex);
    let fill: string;
    if (value === undefined) {
      fill = NO_DATA_FILL;
    } else if (activeTestDef?.limitLow !== undefined && value < activeTestDef.limitLow) {
      fill = SPEC_FAIL_LOW;
    } else if (activeTestDef?.limitHigh !== undefined && value > activeTestDef.limitHigh) {
      fill = SPEC_FAIL_HIGH;
    } else {
      fill = SPEC_PASS_FILL;
    }
    rectangles.push({
      x: die.physX, y: die.physY, width: rw, height: rh,
      fill, type: 'value', metadata: die.metadata,
      path: rectanglePath({ x: die.physX, y: die.physY }, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'value') {
    const value = getDieTestValue(die, testNumber, fallbackIndex);
    let fill: string;
    if (value === undefined) {
      fill = NO_DATA_FILL;
    } else if (activeTestDef?.limitLow !== undefined && value < activeTestDef.limitLow) {
      fill = SPEC_FAIL_LOW;
    } else if (activeTestDef?.limitHigh !== undefined && value > activeTestDef.limitHigh) {
      fill = SPEC_FAIL_HIGH;
    } else {
      fill = colorFns.forValue(normalize(value));
    }
    rectangles.push({
      x: die.physX, y: die.physY, width: rw, height: rh,
      fill, type: 'value', metadata: die.metadata,
      path: rectanglePath({ x: die.physX, y: die.physY }, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'hardBin' || plotMode === 'softBin') {
    const bin = getBin(die);
    const fill = bin != null
      ? (binDefMap?.get(bin)?.color ?? colorFns.forBin(bin))
      : '#d6d9dd';
    rectangles.push({
      x: die.physX, y: die.physY, width: rw, height: rh,
      fill, type: plotMode, metadata: die.metadata,
      path: rectanglePath({ x: die.physX, y: die.physY }, rw, rh, transform),
    });
    return;
  }

  // stackedValues / stackedBins: aggregated scalar in testValues[0] (preferred) or values[0].
  const aggValue = getDieTestValue(die, 0, 0);
  const fill = aggValue !== undefined ? colorFns.forValue(normalize(aggValue)) : '#d6d9dd';
  rectangles.push({
    x: die.physX, y: die.physY, width: rw, height: rh,
    fill, type: 'value', metadata: die.metadata,
    path: rectanglePath({ x: die.physX, y: die.physY }, rw, rh, transform),
  });
}

function buildXYIndicatorOverlay(
  wafer: Wafer,
  transform: TransformState,
  texts: SceneText[]
): SceneOverlay[] {
  // Anchor is fixed at the bottom-left corner in data space (outside the wafer circle).
  // 0.9 per axis → distance ≈ 1.27 × radius: outside the circle but inside the chart area.
  // Do NOT transform the anchor — it stays in the corner regardless of wafer rotation/flip.
  // Only the arrow directions rotate, so they still correctly indicate the data axes.
  const len = wafer.radius * 0.15;
  const xDir = transformVector(len, 0, transform);
  const yDir = transformVector(0, len, transform);
  // Place anchor in the corner the arrows point away from, so they never clip.
  const signX = (xDir.x + yDir.x) >= 0 ? -1 : 1;
  const signY = (xDir.y + yDir.y) >= 0 ? -1 : 1;
  const anchor = {
    x: wafer.center.x + signX * wafer.radius * 0.9,
    y: wafer.center.y + signY * wafer.radius * 0.9,
  };
  const xTip = { x: anchor.x + xDir.x, y: anchor.y + xDir.y };
  const yTip = { x: anchor.x + yDir.x, y: anchor.y + yDir.y };

  texts.push(
    { x: xTip.x + xDir.x * 0.35, y: xTip.y + xDir.y * 0.35, text: '+X', fontSize: 10, color: '#cc3300', align: 'center' },
    { x: yTip.x + yDir.x * 0.35, y: yTip.y + yDir.y * 0.35, text: '+Y', fontSize: 10, color: '#0044cc', align: 'center' },
  );

  return [
    { kind: 'xy-indicator', path: polylinePath([anchor, xTip]), lineColor: '#cc3300', lineWidth: 2 },
    { kind: 'xy-indicator', path: polylinePath([anchor, yTip]), lineColor: '#0044cc', lineWidth: 2 },
  ];
}

/**
 * Build a renderer-agnostic scene from a wafer, dies, and display options.
 *
 * ```ts
 * buildScene(wafer, dies, { plotMode: 'hardBin', reticles })
 * ```
 */
export function buildScene(
  wafer: Wafer,
  dies: Die[],
  options: SceneOptions = {},
): Scene {
  const reticles = options.reticles ?? [];

  const {
    plotMode = 'value',
    showText = false,
    showReticle = false,
    showProbePath = false,
    ringCount = 4,
    showRingBoundaries = false,
    showQuadrantBoundaries = false,
    showXYIndicator = false,
    dieGap = 1,
    colorScheme = 'color',
    highlightBin,
    interactiveTransform,
    valueRange: explicitRange,
    testDefs,
    hbinDefs,
    sbinDefs,
    testIndex = 0,
    fallbackFormat = 'engineering' as const,
    aggrMethod,
    lotSize,
    dataAxisFlip,
    isLotStack = false,
    logScale: logScaleOption,
    colorbarRangeMode = 'spec' as const,
  } = options;

  // Total effective axis flip for display: data-pipeline flip XOR interactive flip.
  const axisFlip = {
    x: (dataAxisFlip?.x ?? false) !== (interactiveTransform?.flipX ?? false),
    y: (dataAxisFlip?.y ?? false) !== (interactiveTransform?.flipY ?? false),
  };

  // Hard and soft bins have independent number spaces — select the correct def map for the
  // current plot mode so bin 5 in hardbin-space and bin 5 in softbin-space can have different names.
  const hbinDefMap: BinDefMap | null = hbinDefs ? new Map(hbinDefs.map(d => [d.bin, d])) : null;
  const sbinDefMap: BinDefMap | null = sbinDefs ? new Map(sbinDefs.map(d => [d.bin, d])) : null;
  const binDefMap: BinDefMap | null  = plotMode === 'softBin' ? sbinDefMap : hbinDefMap;

  const scheme = getColorScheme(colorScheme);

  const colorFns: ColorFns = {
    forValue: scheme.forValue,
    forBin:   scheme.forBin,
  };

  // Resolve testIndex (toolbar cursor) → canonical test number for getDieTestValue.
  let { testNumber: activeTestNumber, fallbackIndex: activeTestFallback } =
    resolveTestNumber(testIndex, testDefs);

  // When no testDefs are provided the toolbar passes actual testNumbers as testIndex.
  // If the resolved testNumber doesn't exist in any die (e.g. default testIndex=0 but data
  // uses keys like 1010), fall back to the lowest key actually present in the dies.
  if (!testDefs?.length && plotMode === 'value') {
    const hasKey = dies.some(d => d.testValues && activeTestNumber in d.testValues);
    if (!hasKey) {
      const firstKey = dies.reduce<number | undefined>((min, d) => {
        if (!d.testValues) return min;
        const keys = Object.keys(d.testValues).map(Number);
        const lo = keys.length ? Math.min(...keys) : undefined;
        return lo !== undefined && (min === undefined || lo < min) ? lo : min;
      }, undefined);
      if (firstKey !== undefined) {
        activeTestNumber  = firstKey;
        activeTestFallback = firstKey;
      }
    }
  }

  // Resolve active test def now — needed for limit-based range defaulting below.
  const activeTestDef = testDefs?.find(t => (t.index ?? t.testNumber) === testIndex);

  // Compute value range for normalization.
  // For stackedValues/stackedBins the aggregated scalar sits at testNumber=0.
  let vMin: number;
  let vMax: number;
  if (explicitRange) {
    [vMin, vMax] = explicitRange;
  } else if (
    plotMode === 'value' &&
    colorbarRangeMode === 'spec' &&
    activeTestDef &&
    (activeTestDef.limitLow !== undefined || activeTestDef.limitHigh !== undefined)
  ) {
    // Colorbar spans the spec window. Data extents fill whichever limit side is absent.
    let lo = Infinity, hi = -Infinity;
    for (const die of dies) {
      const v = getDieTestValue(die, activeTestNumber, activeTestFallback);
      if (v !== undefined) {
        if (v < lo) lo = v;
        if (v > hi) hi = v;
      }
    }
    vMin = activeTestDef.limitLow  !== undefined ? activeTestDef.limitLow  : (isFinite(lo) ? lo : 0);
    vMax = activeTestDef.limitHigh !== undefined ? activeTestDef.limitHigh : (isFinite(hi) ? hi : 1);
  } else {
    let lo = Infinity, hi = -Infinity;
    for (const die of dies) {
      const v = plotMode === 'stackedValues' || plotMode === 'stackedBins' || plotMode === 'stackedSoftBins'
        ? getDieTestValue(die, 0, 0)
        : getDieTestValue(die, activeTestNumber, activeTestFallback);
      if (v !== undefined) {
        if (v < lo) lo = v;
        if (v > hi) hi = v;
      }
    }
    vMin = isFinite(lo) ? lo : 0;
    vMax = isFinite(hi) ? hi : 1;
  }
  if (vMin === vMax) vMax = vMin + 1;

  // Resolve effective log scale: explicit option overrides per-test TestDef default.
  // (activeTestDef already resolved above)
  const wantsLogScale = logScaleOption ?? activeTestDef?.logScale ?? false;
  const logScaleValid = wantsLogScale && vMin > 0 && vMax > 0;
  const logScale      = logScaleValid;

  let normalize: (v: number) => number;
  if (logScaleValid) {
    const logMin   = Math.log10(vMin);
    const logRange = Math.log10(vMax) - logMin;
    normalize = (v: number) => {
      if (v <= 0) return 0;
      return Math.max(0, Math.min(1, (Math.log10(v) - logMin) / logRange));
    };
  } else {
    normalize = (v: number) => Math.max(0, Math.min(1, (v - vMin) / (vMax - vMin)));
  }

  const transform = normalizeTransform(wafer, interactiveTransform);

  // Notch direction in display space (post-transform unit vector).
  let notchDir: { x: number; y: number } | null = null;
  if (wafer.notch) {
    const θ0 = notchAngle(wafer.notch.type);
    const tv = transformVector(Math.cos(θ0) * wafer.radius, Math.sin(θ0) * wafer.radius, transform);
    const len = Math.hypot(tv.x, tv.y);
    if (len > 0) notchDir = { x: tv.x / len, y: tv.y / len };
  }

  // Cap the visual kerf gap at 12 % of the smallest die dimension so that
  // normalized-unit scenes (die pitch ≈ 1) remain visible. No effect for
  // standard 10 mm dies: min(1, 10 × 0.12 = 1.2) = 1.
  const minDim = dies.reduce((m, d) => Math.min(m, d.width, d.height), Infinity);
  const gap = Number.isFinite(minDim) ? Math.min(dieGap, minDim * 0.12) : dieGap;

  const rectangles: SceneRect[] = [];
  const hoverPoints: SceneHoverPoint[] = [];
  // Pre-transformed dies — positions rotated/flipped around wafer centre.
  // Only the physX/physY centre moves; die.x/y/width/height/hbin/sbin/values are unchanged.
  const transformedDies = (transform.rotation || transform.flipX || transform.flipY)
    ? dies.map(d => {
        const tp = transformPoint({ x: d.physX, y: d.physY }, wafer.center, transform);
        return { ...d, physX: tp.x, physY: tp.y };
      })
    : dies;

  for (const tdie of transformedDies) {
    pushDieRectangles(rectangles, tdie, plotMode, transform, gap, colorFns, highlightBin, normalize, activeTestNumber, activeTestFallback, binDefMap, activeTestDef);
    hoverPoints.push({ x: tdie.physX, y: tdie.physY, text: buildHoverText(tdie, plotMode, testDefs, hbinDefs, sbinDefs, fallbackFormat, aggrMethod, lotSize) });
  }

  const texts: SceneText[] = showText ? generateTextOverlay(transformedDies, {
    plotMode, colorFns, normalize, testIndex,
    valueRange: [vMin, vMax], testDefs, fallbackFormat,
  }) : [];
  const overlays = buildBoundaryOverlay(wafer, transform);

  if (showRingBoundaries) overlays.push(...buildRingOverlays(wafer, transform, ringCount));
  if (showQuadrantBoundaries) overlays.push(...buildQuadrantOverlays(wafer, transform));
  if (showReticle) overlays.push(...buildReticleOverlays(reticles, wafer, transform));
  if (showProbePath) overlays.push(...buildProbeOverlay(dies));
  if (showXYIndicator) overlays.push(...buildXYIndicatorOverlay(wafer, transform, texts));

  return {
    rectangles,
    hoverPoints,
    texts,
    overlays,
    plotMode,
    colorScheme,
    metadata: wafer.metadata ?? null,
    dies,
    valueRange: [vMin, vMax],
    testDefs,
    hbinDefs,
    sbinDefs,
    testIndex,
    logScale,
    aggrMethod,
    lotSize,
    axisFlip,
    rotation: ((transform.rotation % 360) + 360) % 360,
    hasReticle: reticles.length > 0,
    isLotStack,
    waferCenter: wafer.center,
    waferRadius: wafer.radius,
    notchDir,
  };
}

// ── Die lookup helpers ────────────────────────────────────────────────────────

/**
 * Return a stable string key for a die — guaranteed format `"i,j"`.
 * Use this for Map keys and post-enrichment lookups instead of ad-hoc template literals.
 *
 * ```ts
 * const map = new Map(result.dies.map(d => [getDieKey(d), d]));
 * const die = map.get(getDieKey({ x: 3, y: -2 }));
 * ```
 */
export function getDieKey(die: { x: number; y: number }): string {
  return `${die.x},${die.y}`;
}

/**
 * Return the die that a Plotly click or hover event points to.
 *
 * The hover scatter trace stores one point per die, indexed parallel to
 * `scene.dies`.  Pass the raw Plotly event object directly.
 *
 * ```ts
 * chart.on('plotly_click', ev => {
 *   const die = getDieAtPoint(scene, ev);
 *   if (die) console.log(die.x, die.y, die.values, die.hbin, die.sbin);
 * });
 * ```
 *
 * Returns `null` when the event doesn't resolve to a known die (e.g. click on
 * an overlay trace rather than the hover trace).
 */
export function getDieAtPoint(
  scene: Scene,
  plotlyEvent: { points?: Array<{ pointIndex?: number; curveNumber?: number }> },
): Die | null {
  const pt = plotlyEvent.points?.[0];
  if (!pt) return null;
  // The hover scatter is always trace 0.  Other traces (text, colorbar ref) are not dies.
  if (pt.curveNumber !== 0) return null;
  const idx = pt.pointIndex;
  if (idx === undefined || idx < 0 || idx >= scene.dies.length) return null;
  return scene.dies[idx];
}
