import type { Wafer } from '../core/wafer.js';
import type { Die } from '../core/dies.js';
import type { Reticle } from '../core/reticle.js';
import type { DieMetadata, WaferMetadata } from '../core/metadata.js';
import { rotatePoint } from '../core/transforms.js';
import { contrastTextColor } from './colorMap.js';
import { getColorScheme } from './colorSchemes.js';
import type { TestDef, BinDef } from './buildWaferMap.js';
import { fmt, fmtColorbarAxis } from './fmt.js';

type BinDefMap = Map<number, BinDef>;

export type PlotMode = 'value' | 'hardbin' | 'softbin' | 'stackedValues' | 'stackedBins' | 'stackedSoftBins';

interface Point {
  x: number;
  y: number;
}

export interface SceneRect {
  x: number;
  y: number;
  width: number;
  height: number;
  fill: string | number;
  type: 'hardbin' | 'softbin' | 'value' | 'stacked';
  stack?: number[];
  metadata?: DieMetadata;
  path: string;
}

export interface SceneText {
  x: number;
  y: number;
  text: string;
  fontSize: number;
  color: string;
  align: 'center';
}

export interface SceneHoverPoint {
  x: number;
  y: number;
  text: string;
}

export interface SceneOverlay {
  kind: 'wafer-boundary' | 'reticle' | 'probe-path' | 'ring-boundary' | 'quadrant-boundary' | 'xy-indicator';
  path: string;
  lineColor: string;
  lineWidth: number;
  fill?: string;
}

export interface Scene {
  rectangles: SceneRect[];
  hoverPoints: SceneHoverPoint[];
  texts: SceneText[];
  overlays: SceneOverlay[];
  plotMode: PlotMode;
  colorScheme: string;
  metadata: WaferMetadata | null;
  dies: Die[];
  /** Actual [min, max] of the value data used for color normalization. */
  valueRange: [number, number];
  /** Named test definitions — populated when `testDefs` is passed to `buildWaferMap`. */
  testDefs?: TestDef[];
  /** Named hard bin definitions (for `bins[0]`). Independent number space from soft bins. */
  hbinDefs?: BinDef[];
  /** Named soft bin definitions (for `bins[1]`). Independent number space from hard bins. */
  sbinDefs?: BinDef[];
  /** Which `values[]` index is being displayed (for `value` plot mode). Default 0. */
  testIndex: number;
  /** Which `bins[]` index is being displayed (for `hardbin`/`softbin` plot modes). Default 0. */
  binIndex: number;
  /** Aggregation method label for `stackedValues` hover tooltips (e.g. `'mean'`). */
  aggrMethod?: string;
  /** Total wafers in lot — for `stackedBins` hover percentage calculation. */
  lotSize?: number;
  /** Total effective axis flip for tick labels (data-pipeline flip XOR interactive flip). */
  axisFlip: { x: boolean; y: boolean };
  /** Total effective rotation in degrees (wafer orientation + interactive rotation). */
  rotation: number;
  /** True when reticle geometry is present — used to conditionally show the reticle toolbar button. */
  hasReticle: boolean;
  /** True when the scene was built from lot-aggregated data (lotStack). Controls toolbar stacked-mode visibility. */
  isLotStack: boolean;
}

export interface SceneOptions {
  plotMode?: PlotMode;
  showText?: boolean;
  showReticle?: boolean;
  showProbePath?: boolean;
  ringCount?: number;
  showRingBoundaries?: boolean;
  showQuadrantBoundaries?: boolean;
  showXYIndicator?: boolean;
  dieGap?: number;
  /** Named colour scheme — any scheme registered via registerColorScheme(). Default: 'default'. */
  colorScheme?: string;
  highlightBin?: number;
  interactiveTransform?: { rotation?: number; flipX?: boolean; flipY?: boolean };
  /**
   * Explicit [min, max] for value colour normalization. When omitted the range
   * is auto-computed from the die values present in the scene.
   */
  valueRange?: [number, number];
  /**
   * Reticle rectangles to overlay on the map.
   * Generated by `generateReticleGrid` or the `reticle` option on `buildWaferMap`.
   */
  reticles?: Reticle[];
  /** Named test definitions — one per `values[]` entry. */
  testDefs?: TestDef[];
  /**
   * Named hard bin definitions — one per distinct `bins[0]` value.
   * Hard and soft bin number spaces are independent (STDF V4: both 0–32767).
   */
  hbinDefs?: BinDef[];
  /**
   * Named soft bin definitions — one per distinct `bins[1]` value.
   * Soft bins are the logical test-program classification; hard bins are the physical sort result.
   */
  sbinDefs?: BinDef[];
  /**
   * Which `values[]` index to display in `value` plot mode. Default `0`.
   * When `testDefs` is provided, the toolbar mode dropdown offers one item per test.
   */
  testIndex?: number;
  /**
   * Which `bins[]` index to display in `hardbin` / `softbin` plot modes. Default `0`.
   */
  binIndex?: number;
  /**
   * Format to use for unitless values outside the normal display range [0.1, 9999].
   * `'engineering'` (default): multiples-of-3 exponent notation (e.g. `12E-6`).
   * `'si'`: SI prefix with no unit suffix (e.g. `12 µ`).
   * Values with a unit always use SI prefix regardless of this setting.
   */
  fallbackFormat?: 'si' | 'engineering';
  /**
   * Aggregation method label shown in hover tooltips for `stackedValues` mode.
   * E.g. `'mean'`, `'median'`, `'stddev'`, `'min'`, `'max'`.
   */
  aggrMethod?: string;
  /**
   * Total number of wafers in the lot — used to compute bin occurrence percentage
   * in `stackedBins` hover tooltips.
   */
  lotSize?: number;
  /**
   * Axis flip baked in by the data pipeline (for LL/LR/UL/UR origins or explicit
   * `xAxisDirection`/`yAxisDirection`). Combined with `interactiveTransform` flip
   * to produce the total effective axis flip for tick labels.
   */
  dataAxisFlip?: { x: boolean; y: boolean };
  /** Set to true when the scene is built from lot-aggregated data (lotStack). */
  isLotStack?: boolean;
}

/** @deprecated Use {@link SceneOptions} */
export type BuildSceneOptions = SceneOptions;

interface TransformState {
  rotation: number;
  flipX: boolean;
  flipY: boolean;
}

interface ColorFns {
  forValue: (t: number) => string;
  forBin: (bin: number) => string;
}

const PARTIAL_DIE_FILL = '#d3d6db';
const DIM_FILL = '#e8e9ea';
const EDGE_EXCLUDED_FILL = '#eceef0';

function normalizeTransform(
  wafer: Wafer,
  interactiveTransform: SceneOptions['interactiveTransform']
): TransformState {
  return {
    rotation: wafer.orientation + (interactiveTransform?.rotation ?? 0),
    flipX: interactiveTransform?.flipX ?? false,
    flipY: interactiveTransform?.flipY ?? false,
  };
}

function transformVector(dx: number, dy: number, transform: TransformState): Point {
  const rad = (transform.rotation * Math.PI) / 180;
  const cos = Math.cos(rad);
  const sin = Math.sin(rad);
  let x = dx * cos - dy * sin;
  let y = dx * sin + dy * cos;

  if (transform.flipX) x = -x;
  if (transform.flipY) y = -y;

  return { x, y };
}

function toPath(points: Point[]): string {
  return `${points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`).join(' ')} Z`;
}

function polylinePath(points: Point[], close = false): string {
  if (!points.length) return '';
  const path = points.map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`).join(' ');
  return close ? `${path} Z` : path;
}

function transformPoint(point: Point, center: Point, transform: TransformState): Point {
  let next = transform.rotation ? rotatePoint(point.x, point.y, transform.rotation, center.x, center.y) : point;
  if (transform.flipX) next = { x: 2 * center.x - next.x, y: next.y };
  if (transform.flipY) next = { x: next.x, y: 2 * center.y - next.y };
  return next;
}

/**
 * Returns the boundary point at `angle` for a wafer with an orientation flat
 * (chord cut).  V-notch wafers are handled separately in buildBoundaryOverlay.
 */
function boundaryPointAtAngle(wafer: Wafer, angle: number): Point {
  const { center, radius, notch } = wafer;
  let x = center.x + radius * Math.cos(angle);
  let y = center.y + radius * Math.sin(angle);

  if (!notch) return { x, y };

  const chordDist = Math.sqrt(radius ** 2 - (notch.length / 2) ** 2);
  const halfLen   = notch.length / 2;
  const dx = x - center.x;
  const dy = y - center.y;

  if (notch.type === 'bottom' && dy < -chordDist) {
    y = center.y - chordDist;
    x = center.x + Math.max(-halfLen, Math.min(halfLen, dx));
  } else if (notch.type === 'top' && dy > chordDist) {
    y = center.y + chordDist;
    x = center.x + Math.max(-halfLen, Math.min(halfLen, dx));
  } else if (notch.type === 'left' && dx < -chordDist) {
    x = center.x - chordDist;
    y = center.y + Math.max(-halfLen, Math.min(halfLen, dy));
  } else if (notch.type === 'right' && dx > chordDist) {
    x = center.x + chordDist;
    y = center.y + Math.max(-halfLen, Math.min(halfLen, dy));
  }

  return { x, y };
}

function rectanglePath(center: Point, width: number, height: number, transform: TransformState): string {
  const corners = [
    transformVector(-width / 2, -height / 2, transform),
    transformVector(width / 2, -height / 2, transform),
    transformVector(width / 2, height / 2, transform),
    transformVector(-width / 2, height / 2, transform),
  ].map((corner) => ({ x: center.x + corner.x, y: center.y + corner.y }));

  return toPath(corners);
}

function formatValueLabel(values: number[], tickFmt: (v: number) => string): string {
  return values.map(tickFmt).join(' / ');
}


function fontSizeForDie(die: Die, text: string): number {
  const minSide = Math.max(1, Math.min(die.width, die.height));
  const widthBudget = die.width / Math.max(text.length, 1);
  return Math.max(8, Math.min(16, Math.round(Math.min(minSide * 0.55, widthBudget * 1.8))));
}

function buildHoverText(
  die: Die,
  plotMode: PlotMode,
  testDefs?: TestDef[],
  hbinDefs?: BinDef[],
  sbinDefs?: BinDef[],
  fallbackFormat?: 'si' | 'engineering',
  aggrMethod?: string,
  lotSize?: number,
): string {
  const lines: string[] = [`Die (${die.i}, ${die.j})`];

  if (plotMode === 'stackedValues') {
    // Show only the aggregated test value for this card's parameter (values[0]).
    const v = die.values?.[0];
    if (v !== undefined) {
      const def   = testDefs?.[0];
      const name  = def?.name ?? 'Value';
      const method = aggrMethod ? ` (${aggrMethod})` : '';
      lines.push(`${name}${method}: ${fmt(v, def?.unit, fallbackFormat)}`);
    }
  } else if (plotMode === 'stackedBins' || plotMode === 'stackedSoftBins') {
    // Show count and percentage for this card's bin (values[0] = count, bins[0] = targetBin).
    const count = die.values?.[0];
    const bin   = die.bins?.[0];
    if (count !== undefined) {
      const pct     = lotSize ? ` (${((count / lotSize) * 100).toFixed(0)}%)` : '';
      const defMap  = plotMode === 'stackedSoftBins'
        ? (sbinDefs ? new Map(sbinDefs.map(d => [d.bin, d])) : null)
        : (hbinDefs ? new Map(hbinDefs.map(d => [d.bin, d])) : null);
      const binLabel = bin !== undefined
        ? (defMap?.get(bin)?.name ? `${bin} · ${defMap.get(bin)!.name}` : `Bin ${bin}`)
        : 'Bin';
      lines.push(`${binLabel}: ${count}${pct}`);
    }
  } else {
    // Standard modes: show all values with test names, then bins.
    if (die.values?.length) {
      if (testDefs?.length) {
        const parts = die.values.map((v, i) => {
          const def   = testDefs.find(t => t.index === i);
          const label = def?.name ?? `Test ${i}`;
          return `${label}: ${fmt(v, def?.unit, fallbackFormat)}`;
        });
        lines.push(parts.join('<br>'));
      } else {
        lines.push(`Values: ${die.values.map((v) => fmt(v, undefined, fallbackFormat)).join(' / ')}`);
      }
    }

    if (die.bins?.length) {
      const hbinMap    = hbinDefs ? new Map(hbinDefs.map(d => [d.bin, d])) : null;
      const sbinMap    = sbinDefs ? new Map(sbinDefs.map(d => [d.bin, d])) : null;
      const hasAnyDefs = hbinMap || sbinMap;
      if (hasAnyDefs) {
        const parts = die.bins.map((b, i) => {
          const defMap = i === 0 ? hbinMap : i === 1 ? sbinMap : null;
          const name   = defMap?.get(b)?.name;
          const value  = name ? `${b} · ${name}` : String(b);
          const label  = i === 0 ? 'HBin' : i === 1 ? 'SBin' : `Bin[${i}]`;
          return `${label}: ${value}`;
        });
        lines.push(parts.join(' &nbsp;·&nbsp; '));
      } else {
        lines.push(`Bins: ${die.bins.map((b) => `B${b}`).join(' | ')}`);
      }
    }
  }

  if (die.retestCount !== undefined) lines.push(`Retests: ${die.retestCount}`);
  if (die.partial) lines.push('<i>partial die</i>');
  if (die.probeIndex !== undefined) lines.push(`Probe: #${die.probeIndex}`);

  if (die.metadata) {
    for (const [key, value] of Object.entries(die.metadata)) {
      if (value === undefined || value === null || key === 'customFields') continue;
      lines.push(`${key}: ${String(value)}`);
    }
    if (die.metadata.customFields) {
      for (const [key, value] of Object.entries(die.metadata.customFields)) {
        if (value === undefined || value === null) continue;
        lines.push(`${key}: ${String(value)}`);
      }
    }
  }

  return lines.join('<br>');
}


export function generateTextOverlay(
  dies: Die[],
  options: {
    plotMode: PlotMode;
    colorFns: ColorFns;
    normalize: (v: number) => number;
    testIndex: number;
    binIndex: number;
    valueRange: [number, number];
    testDefs?: TestDef[];
    fallbackFormat?: 'si' | 'engineering';
  },
): SceneText[] {
  const { plotMode, colorFns, normalize, testIndex, binIndex, valueRange, testDefs, fallbackFormat } = options;

  // Build a tick formatter matched to the colorbar scale so die labels are consistent.
  const testDef = testDefs?.find(t => t.index === testIndex);
  const { tickFmt } = fmtColorbarAxis(valueRange[1], testDef?.name, testDef?.unit, fallbackFormat);

  return dies.flatMap((die) => {
    let text = '';
    let color = '#111111';

    if (plotMode === 'value') {
      const v = die.values?.[testIndex];
      if (v === undefined) return [];
      text = formatValueLabel([v], tickFmt);
      color = contrastTextColor(colorFns.forValue(normalize(v)));
    } else if (plotMode === 'hardbin' || plotMode === 'softbin') {
      const bin = die.bins?.[binIndex];
      if (bin === undefined) return [];
      text = String(bin);
      color = contrastTextColor(colorFns.forBin(bin));
    } else {
      // stackedValues / stackedBins: single aggregated value in values[testIndex] or values[0]
      const v = die.values?.[testIndex] ?? die.values?.[0];
      if (v === undefined) return [];
      text = formatValueLabel([v], tickFmt);
      color = contrastTextColor(colorFns.forValue(normalize(v)));
    }

    return [{
      x: die.x,
      y: die.y,
      text,
      fontSize: fontSizeForDie(die, text),
      color,
      align: 'center',
    }];
  });
}

/**
 * Notch direction angle in radians.
 * Wafer convention: bottom notch points downward (−Y), which is angle −π/2.
 */
function notchAngle(type: 'top' | 'bottom' | 'left' | 'right'): number {
  if (type === 'top')    return  Math.PI / 2;
  if (type === 'bottom') return -Math.PI / 2;
  if (type === 'left')   return  Math.PI;
  return 0; // right
}

/**
 * Build the wafer boundary overlay, choosing between two rendering modes:
 *
 * - **Flat** (≤ 150 mm): straight chord cut — `boundaryPointAtAngle` handles it.
 * - **V-notch** (> 150 mm): three explicit points (entry → apex → exit) are
 *   spliced into the uniform circle trace so the notch renders as a sharp
 *   triangular indentation (~3.5 mm wide, ~1.25 mm deep — SEMI M1 standard).
 */
function buildBoundaryOverlay(wafer: Wafer, transform: TransformState, steps = 720): SceneOverlay[] {
  const { center, radius, notch } = wafer;

  // Determine rendering style from diameter — same threshold used in resolveNotch.
  const isVNotch = notch !== undefined && wafer.diameter > 150;

  if (!isVNotch) {
    // Flat / no alignment feature — uniform angle sweep with chord clamping.
    const points: Point[] = [];
    for (let index = 0; index <= steps; index++) {
      const angle = (2 * Math.PI * index) / steps;
      points.push(transformPoint(boundaryPointAtAngle(wafer, angle), center, transform));
    }
    return [{ kind: 'wafer-boundary', path: polylinePath(points, true), lineColor: '#111111', lineWidth: 2 }];
  }

  // V-notch: build circle, then splice in the triangular indentation.
  // SEMI M1: half-width at surface ≈ 1.75 mm, depth ≈ 1.25 mm.
  const notchDepth     = 1.25;
  const notchHalfWidth = notch.length; // set by createWafer = 1.75 for large wafers
  const θ0             = notchAngle(notch.type);
  const Δ              = Math.atan2(notchHalfWidth, radius); // angular half-span (~0.67° for 300 mm)
  const apexRadius     = radius - notchDepth;

  // Collect uniform circle points, skipping any that fall inside the notch zone.
  const points: Point[] = [];
  let notchInserted = false;

  for (let index = 0; index <= steps; index++) {
    const angle = (2 * Math.PI * index) / steps;

    // Normalise angle difference to (−π, π].
    let dθ = angle - θ0;
    while (dθ >  Math.PI) dθ -= 2 * Math.PI;
    while (dθ < -Math.PI) dθ += 2 * Math.PI;

    if (Math.abs(dθ) <= Δ) {
      // Inside the notch arc — insert V geometry once at this crossing.
      if (!notchInserted) {
        notchInserted = true;
        const entry = { x: center.x + radius * Math.cos(θ0 - Δ), y: center.y + radius * Math.sin(θ0 - Δ) };
        const apex  = { x: center.x + apexRadius * Math.cos(θ0), y: center.y + apexRadius * Math.sin(θ0) };
        const exit_ = { x: center.x + radius * Math.cos(θ0 + Δ), y: center.y + radius * Math.sin(θ0 + Δ) };
        points.push(
          transformPoint(entry, center, transform),
          transformPoint(apex,  center, transform),
          transformPoint(exit_, center, transform),
        );
      }
      continue;
    }

    points.push(transformPoint({ x: center.x + radius * Math.cos(angle), y: center.y + radius * Math.sin(angle) }, center, transform));
  }

  return [{ kind: 'wafer-boundary', path: polylinePath(points, true), lineColor: '#111111', lineWidth: 2 }];
}

function buildRingOverlays(wafer: Wafer, transform: TransformState, ringCount: number, steps = 360): SceneOverlay[] {
  const overlays: SceneOverlay[] = [];
  const safeRingCount = Math.max(1, Math.floor(ringCount));

  for (let ring = 1; ring < safeRingCount; ring++) {
    const radius = (wafer.radius * ring) / safeRingCount;
    const points: Point[] = [];

    for (let index = 0; index <= steps; index++) {
      const angle = (2 * Math.PI * index) / steps;
      const localPoint = {
        x: wafer.center.x + radius * Math.cos(angle),
        y: wafer.center.y + radius * Math.sin(angle),
      };
      points.push(transformPoint(localPoint, wafer.center, transform));
    }

    overlays.push({
      kind: 'ring-boundary',
      path: polylinePath(points, true),
      lineColor: 'rgba(255,255,255,0.7)',
      lineWidth: 1.5,
    });
  }

  return overlays;
}

function buildQuadrantOverlays(wafer: Wafer, transform: TransformState): SceneOverlay[] {
  const angles = [0, Math.PI / 2];

  return angles.map((angle) => {
    const start = transformPoint(boundaryPointAtAngle(wafer, angle), wafer.center, transform);
    const end = transformPoint(boundaryPointAtAngle(wafer, angle + Math.PI), wafer.center, transform);
    return {
      kind: 'quadrant-boundary',
      path: polylinePath([start, end]),
      lineColor: 'rgba(255,255,255,0.7)',
      lineWidth: 1.5,
    };
  });
}

function buildReticleOverlays(reticles: Reticle[], wafer: Wafer, transform: TransformState): SceneOverlay[] {
  return reticles.map((reticle) => {
    const rotatedCenter = transform.rotation
      ? rotatePoint(reticle.x, reticle.y, transform.rotation, wafer.center.x, wafer.center.y)
      : { x: reticle.x, y: reticle.y };

    const transformedCenter = {
      x: transform.flipX ? 2 * wafer.center.x - rotatedCenter.x : rotatedCenter.x,
      y: transform.flipY ? 2 * wafer.center.y - rotatedCenter.y : rotatedCenter.y,
    };

    return {
      kind: 'reticle',
      path: rectanglePath(transformedCenter, reticle.width, reticle.height, transform),
      lineColor: 'rgba(0,100,220,0.45)',
      lineWidth: 1,
      fill: 'rgba(0,0,0,0)',
    };
  });
}

function buildProbeOverlay(dies: Die[]): SceneOverlay[] {
  const ordered = dies
    .filter((die) => die.probeIndex !== undefined)
    .sort((left, right) => (left.probeIndex ?? 0) - (right.probeIndex ?? 0));

  if (!ordered.length) return [];

  return [{
    kind: 'probe-path',
    path: polylinePath(ordered.map((die) => ({ x: die.x, y: die.y }))),
    lineColor: 'rgba(220,80,0,0.55)',
    lineWidth: 1,
  }];
}

function pushDieRectangles(
  rectangles: SceneRect[],
  die: Die,
  plotMode: PlotMode,
  transform: TransformState,
  gap: number,
  colorFns: ColorFns,
  highlightBin: number | undefined,
  normalize: (v: number) => number,
  testIndex: number,
  binIndex: number,
  binDefMap: Map<number, BinDef> | null,
): void {
  const rw = die.width - gap;
  const rh = die.height - gap;

  if (die.partial) {
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill: PARTIAL_DIE_FILL, type: 'stacked', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (die.edgeExcluded) {
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill: EDGE_EXCLUDED_FILL, type: 'stacked', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (highlightBin !== undefined &&
      (plotMode === 'hardbin' || plotMode === 'softbin') &&
      die.bins?.[binIndex] !== highlightBin) {
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill: DIM_FILL, type: 'hardbin', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'value') {
    const value = die.values?.[testIndex];
    const fill = value !== undefined ? colorFns.forValue(normalize(value)) : '#d6d9dd';
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill, type: 'value', metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  if (plotMode === 'hardbin' || plotMode === 'softbin') {
    const bin = die.bins?.[binIndex];
    const fill = bin != null
      ? (binDefMap?.get(bin)?.color ?? colorFns.forBin(bin))
      : '#d6d9dd';
    rectangles.push({
      x: die.x, y: die.y, width: rw, height: rh,
      fill, type: plotMode, metadata: die.metadata,
      path: rectanglePath(die, rw, rh, transform),
    });
    return;
  }

  // stackedValues / stackedBins: lot-aggregated data, single colour per die.
  // The caller pre-aggregates dies (aggregateValues / aggregateBinCounts) and
  // passes them with values[0] holding the aggregated scalar. Render like 'value'.
  const aggValue = die.values?.[testIndex] ?? die.values?.[0];
  const fill = aggValue !== undefined ? colorFns.forValue(normalize(aggValue)) : '#d6d9dd';
  rectangles.push({
    x: die.x, y: die.y, width: rw, height: rh,
    fill, type: 'value', metadata: die.metadata,
    path: rectanglePath(die, rw, rh, transform),
  });
}

function buildXYIndicatorOverlay(
  wafer: Wafer,
  transform: TransformState,
  texts: SceneText[]
): SceneOverlay[] {
  // Anchor is fixed at the bottom-left corner in data space (outside the wafer circle).
  // 0.9 per axis → distance ≈ 1.27 × radius: outside the circle but inside the chart area.
  // Do NOT transform the anchor — it stays in the corner regardless of wafer rotation/flip.
  // Only the arrow directions rotate, so they still correctly indicate the data axes.
  const len = wafer.radius * 0.15;
  const xDir = transformVector(len, 0, transform);
  const yDir = transformVector(0, len, transform);
  // Place anchor in the corner the arrows point away from, so they never clip.
  const signX = (xDir.x + yDir.x) >= 0 ? -1 : 1;
  const signY = (xDir.y + yDir.y) >= 0 ? -1 : 1;
  const anchor = {
    x: wafer.center.x + signX * wafer.radius * 0.9,
    y: wafer.center.y + signY * wafer.radius * 0.9,
  };
  const xTip = { x: anchor.x + xDir.x, y: anchor.y + xDir.y };
  const yTip = { x: anchor.x + yDir.x, y: anchor.y + yDir.y };

  texts.push(
    { x: xTip.x + xDir.x * 0.35, y: xTip.y + xDir.y * 0.35, text: '+X', fontSize: 10, color: '#cc3300', align: 'center' },
    { x: yTip.x + yDir.x * 0.35, y: yTip.y + yDir.y * 0.35, text: '+Y', fontSize: 10, color: '#0044cc', align: 'center' },
  );

  return [
    { kind: 'xy-indicator', path: polylinePath([anchor, xTip]), lineColor: '#cc3300', lineWidth: 2 },
    { kind: 'xy-indicator', path: polylinePath([anchor, yTip]), lineColor: '#0044cc', lineWidth: 2 },
  ];
}

/**
 * Build a renderer-agnostic scene from a wafer, dies, and display options.
 *
 * ```ts
 * buildScene(wafer, dies, { plotMode: 'hardbin', reticles })
 * ```
 */
export function buildScene(
  wafer: Wafer,
  dies: Die[],
  options: SceneOptions = {},
): Scene {
  const reticles = options.reticles ?? [];

  const {
    plotMode = 'value',
    showText = false,
    showReticle = false,
    showProbePath = false,
    ringCount = 4,
    showRingBoundaries = false,
    showQuadrantBoundaries = false,
    showXYIndicator = false,
    dieGap = 1,
    colorScheme = 'color',
    highlightBin,
    interactiveTransform,
    valueRange: explicitRange,
    testDefs,
    hbinDefs,
    sbinDefs,
    testIndex = 0,
    binIndex: rawBinIndex,
    fallbackFormat = 'engineering' as const,
    aggrMethod,
    lotSize,
    dataAxisFlip,
    isLotStack = false,
  } = options;

  // Soft bins live in bins[1]; hard bins in bins[0]. Apply the correct default when
  // the caller didn't explicitly supply binIndex.
  const binIndex = rawBinIndex ?? (plotMode === 'softbin' ? 1 : 0);

  // Total effective axis flip for display: data-pipeline flip XOR interactive flip.
  const axisFlip = {
    x: (dataAxisFlip?.x ?? false) !== (interactiveTransform?.flipX ?? false),
    y: (dataAxisFlip?.y ?? false) !== (interactiveTransform?.flipY ?? false),
  };

  // Hard and soft bins have independent number spaces — select the correct def map for the
  // current plot mode so bin 5 in hardbin-space and bin 5 in softbin-space can have different names.
  const hbinDefMap: BinDefMap | null = hbinDefs ? new Map(hbinDefs.map(d => [d.bin, d])) : null;
  const sbinDefMap: BinDefMap | null = sbinDefs ? new Map(sbinDefs.map(d => [d.bin, d])) : null;
  const binDefMap: BinDefMap | null  = plotMode === 'softbin' ? sbinDefMap : hbinDefMap;

  const scheme = getColorScheme(colorScheme);

  const colorFns: ColorFns = {
    forValue: scheme.forValue,
    forBin:   scheme.forBin,
  };

  // Compute value range for normalization. Always range against values[testIndex] only
  // (for stackedValues/stackedBins the aggregated scalar sits in values[0], testIndex=0).
  let vMin: number;
  let vMax: number;
  if (explicitRange) {
    [vMin, vMax] = explicitRange;
  } else {
    let lo = Infinity, hi = -Infinity;
    for (const die of dies) {
      const vals = die.values ?? [];
      const candidates = vals[testIndex] !== undefined ? [vals[testIndex]] : [];
      for (const v of candidates) {
        if (v < lo) lo = v;
        if (v > hi) hi = v;
      }
    }
    vMin = isFinite(lo) ? lo : 0;
    vMax = isFinite(hi) ? hi : 1;
  }
  if (vMin === vMax) vMax = vMin + 1;
  const normalize = (v: number) => Math.max(0, Math.min(1, (v - vMin) / (vMax - vMin)));

  const transform = normalizeTransform(wafer, interactiveTransform);

  // Cap the visual kerf gap at 12 % of the smallest die dimension so that
  // normalized-unit scenes (die pitch ≈ 1) remain visible. No effect for
  // standard 10 mm dies: min(1, 10 × 0.12 = 1.2) = 1.
  const minDim = dies.reduce((m, d) => Math.min(m, d.width, d.height), Infinity);
  const gap = Number.isFinite(minDim) ? Math.min(dieGap, minDim * 0.12) : dieGap;

  const rectangles: SceneRect[] = [];
  const hoverPoints: SceneHoverPoint[] = [];
  // Pre-transformed dies — positions rotated/flipped around wafer centre.
  // Only the x,y centre moves; die.i/j/width/height/bins/values are unchanged.
  const transformedDies = (transform.rotation || transform.flipX || transform.flipY)
    ? dies.map(d => {
        const tp = transformPoint({ x: d.x, y: d.y }, wafer.center, transform);
        return { ...d, x: tp.x, y: tp.y };
      })
    : dies;

  for (const tdie of transformedDies) {
    pushDieRectangles(rectangles, tdie, plotMode, transform, gap, colorFns, highlightBin, normalize, testIndex, binIndex, binDefMap);
    hoverPoints.push({ x: tdie.x, y: tdie.y, text: buildHoverText(tdie, plotMode, testDefs, hbinDefs, sbinDefs, fallbackFormat, aggrMethod, lotSize) });
  }

  const texts: SceneText[] = showText ? generateTextOverlay(transformedDies, {
    plotMode, colorFns, normalize, testIndex, binIndex,
    valueRange: [vMin, vMax], testDefs, fallbackFormat,
  }) : [];
  const overlays = buildBoundaryOverlay(wafer, transform);

  if (showRingBoundaries) overlays.push(...buildRingOverlays(wafer, transform, ringCount));
  if (showQuadrantBoundaries) overlays.push(...buildQuadrantOverlays(wafer, transform));
  if (showReticle) overlays.push(...buildReticleOverlays(reticles, wafer, transform));
  if (showProbePath) overlays.push(...buildProbeOverlay(dies));
  if (showXYIndicator) overlays.push(...buildXYIndicatorOverlay(wafer, transform, texts));

  return {
    rectangles,
    hoverPoints,
    texts,
    overlays,
    plotMode,
    colorScheme,
    metadata: wafer.metadata ?? null,
    dies,
    valueRange: [vMin, vMax],
    testDefs,
    hbinDefs,
    sbinDefs,
    testIndex,
    binIndex,
    aggrMethod,
    lotSize,
    axisFlip,
    rotation: ((transform.rotation % 360) + 360) % 360,
    hasReticle: reticles.length > 0,
    isLotStack,
  };
}

// ── Die lookup helpers ────────────────────────────────────────────────────────

/**
 * Return a stable string key for a die — guaranteed format `"i,j"`.
 * Use this for Map keys and post-enrichment lookups instead of ad-hoc template literals.
 *
 * ```ts
 * const map = new Map(result.dies.map(d => [getDieKey(d), d]));
 * const die = map.get(getDieKey({ i: 3, j: -2 }));
 * ```
 */
export function getDieKey(die: { i: number; j: number }): string {
  return `${die.i},${die.j}`;
}

/**
 * Return the die that a Plotly click or hover event points to.
 *
 * The hover scatter trace stores one point per die, indexed parallel to
 * `scene.dies`.  Pass the raw Plotly event object directly.
 *
 * ```ts
 * chart.on('plotly_click', ev => {
 *   const die = getDieAtPoint(scene, ev);
 *   if (die) console.log(die.i, die.j, die.values, die.bins);
 * });
 * ```
 *
 * Returns `null` when the event doesn't resolve to a known die (e.g. click on
 * an overlay trace rather than the hover trace).
 */
export function getDieAtPoint(
  scene: Scene,
  plotlyEvent: { points?: Array<{ pointIndex?: number; curveNumber?: number }> },
): Die | null {
  const pt = plotlyEvent.points?.[0];
  if (!pt) return null;
  // The hover scatter is always trace 0.  Other traces (text, colorbar ref) are not dies.
  if (pt.curveNumber !== 0) return null;
  const idx = pt.pointIndex;
  if (idx === undefined || idx < 0 || idx >= scene.dies.length) return null;
  return scene.dies[idx];
}
